/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _OPAC_H_RPCGEN
#define _OPAC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct book {
	int id;
	char *name;
	char *author;
	char *category;
	int copies;
};
typedef struct book book;

#define OPAC_PROG 0x3985632
#define OPAC_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define search 1
extern  int * search_1(book *, CLIENT *);
extern  int * search_1_svc(book *, struct svc_req *);
#define reserve 2
extern  int * reserve_1(book *, CLIENT *);
extern  int * reserve_1_svc(book *, struct svc_req *);
#define renew 3
extern  int * renew_1(book *, CLIENT *);
extern  int * renew_1_svc(book *, struct svc_req *);
#define add 4
extern  int * add_1(book *, CLIENT *);
extern  int * add_1_svc(book *, struct svc_req *);
extern int opac_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define search 1
extern  int * search_1();
extern  int * search_1_svc();
#define reserve 2
extern  int * reserve_1();
extern  int * reserve_1_svc();
#define renew 3
extern  int * renew_1();
extern  int * renew_1_svc();
#define add 4
extern  int * add_1();
extern  int * add_1_svc();
extern int opac_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_book (XDR *, book*);

#else /* K&R C */
extern bool_t xdr_book ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_OPAC_H_RPCGEN */
