/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TELLMEDAY_H_RPCGEN
#define _TELLMEDAY_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct date {
	int dd;
	int mm;
	long yy;
};
typedef struct date date;

#define TELL_ME_DAY 0x3987632
#define TELL_ME_DAY_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define no_of_leap_days 1
extern  int * no_of_leap_days_1(date *, CLIENT *);
extern  int * no_of_leap_days_1_svc(date *, struct svc_req *);
#define no_of_days 2
extern  long * no_of_days_1(date *, CLIENT *);
extern  long * no_of_days_1_svc(date *, struct svc_req *);
#define get_day 3
extern  char ** get_day_1(date *, CLIENT *);
extern  char ** get_day_1_svc(date *, struct svc_req *);
extern int tell_me_day_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define no_of_leap_days 1
extern  int * no_of_leap_days_1();
extern  int * no_of_leap_days_1_svc();
#define no_of_days 2
extern  long * no_of_days_1();
extern  long * no_of_days_1_svc();
#define get_day 3
extern  char ** get_day_1();
extern  char ** get_day_1_svc();
extern int tell_me_day_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_date (XDR *, date*);

#else /* K&R C */
extern bool_t xdr_date ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TELLMEDAY_H_RPCGEN */
