/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "tellmeday.h"

bool_t
xdr_date (XDR *xdrs, date *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->dd))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->mm))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->yy))
		 return FALSE;
	return TRUE;
}
