/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "countweekdays.h"

bool_t
xdr_date (XDR *xdrs, date *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->dd))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->mm))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->yy))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_dates (XDR *xdrs, dates *objp)
{
	register int32_t *buf;

	 if (!xdr_date (xdrs, &objp->d1))
		 return FALSE;
	 if (!xdr_date (xdrs, &objp->d2))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg))
		 return FALSE;
	return TRUE;
}
