/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _COUNTWEEKDAYS_H_RPCGEN
#define _COUNTWEEKDAYS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct date {
	int dd;
	int mm;
	long yy;
};
typedef struct date date;

struct dates {
	date d1;
	date d2;
	int arg;
};
typedef struct dates dates;

#define COUNT_DAYS 0x3987642
#define COUNT_DAYS_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define no_leap_years 1
extern  int * no_leap_years_1(date *, CLIENT *);
extern  int * no_leap_years_1_svc(date *, struct svc_req *);
#define no_of_days 2
extern  long * no_of_days_1(date *, CLIENT *);
extern  long * no_of_days_1_svc(date *, struct svc_req *);
#define get_day 3
extern  int * get_day_1(date *, CLIENT *);
extern  int * get_day_1_svc(date *, struct svc_req *);
#define get_no_of_days 4
extern  long * get_no_of_days_1(dates *, CLIENT *);
extern  long * get_no_of_days_1_svc(dates *, struct svc_req *);
#define get_no_of_weekday 5
extern  long * get_no_of_weekday_1(dates *, CLIENT *);
extern  long * get_no_of_weekday_1_svc(dates *, struct svc_req *);
extern int count_days_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define no_leap_years 1
extern  int * no_leap_years_1();
extern  int * no_leap_years_1_svc();
#define no_of_days 2
extern  long * no_of_days_1();
extern  long * no_of_days_1_svc();
#define get_day 3
extern  int * get_day_1();
extern  int * get_day_1_svc();
#define get_no_of_days 4
extern  long * get_no_of_days_1();
extern  long * get_no_of_days_1_svc();
#define get_no_of_weekday 5
extern  long * get_no_of_weekday_1();
extern  long * get_no_of_weekday_1_svc();
extern int count_days_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_date (XDR *, date*);
extern  bool_t xdr_dates (XDR *, dates*);

#else /* K&R C */
extern bool_t xdr_date ();
extern bool_t xdr_dates ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_COUNTWEEKDAYS_H_RPCGEN */
