/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CODA_H_RPCGEN
#define _CODA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct arguments {
	int x;
};
typedef struct arguments arguments;

#define CODA 0x3987632
#define CODA_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define update_file 1
extern  int * update_file_1(char **, CLIENT *);
extern  int * update_file_1_svc(char **, struct svc_req *);
#define check_connection 2
extern  int * check_connection_1(int *, CLIENT *);
extern  int * check_connection_1_svc(int *, struct svc_req *);
extern int coda_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define update_file 1
extern  int * update_file_1();
extern  int * update_file_1_svc();
#define check_connection 2
extern  int * check_connection_1();
extern  int * check_connection_1_svc();
extern int coda_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_arguments (XDR *, arguments*);

#else /* K&R C */
extern bool_t xdr_arguments ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CODA_H_RPCGEN */
