/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TELLMEDAY_H_RPCGEN
#define _TELLMEDAY_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct date {
	int dd;
	int mm;
	int yy[20];
};
typedef struct date date;

struct dates {
	date d1;
	int res[20];
};
typedef struct dates dates;

#define TELL_ME_DAY1 0x1000001
#define TELL_ME_DAY_VERSION1 1

#if defined(__STDC__) || defined(__cplusplus)
#define no_leap_years 1
extern  dates * no_leap_years_1(dates *, CLIENT *);
extern  dates * no_leap_years_1_svc(dates *, struct svc_req *);
extern int tell_me_day1_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define no_leap_years 1
extern  dates * no_leap_years_1();
extern  dates * no_leap_years_1_svc();
extern int tell_me_day1_1_freeresult ();
#endif /* K&R C */

#define TELL_ME_DAY2 0x1000002
#define TELL_ME_DAY_VERSION2 2

#if defined(__STDC__) || defined(__cplusplus)
#define no_of_days 2
extern  dates * no_of_days_2(dates *, CLIENT *);
extern  dates * no_of_days_2_svc(dates *, struct svc_req *);
extern int tell_me_day2_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define no_of_days 2
extern  dates * no_of_days_2();
extern  dates * no_of_days_2_svc();
extern int tell_me_day2_2_freeresult ();
#endif /* K&R C */

#define TELL_ME_DAY3 0x1000003
#define TELL_ME_DAY_VERSION3 3

#if defined(__STDC__) || defined(__cplusplus)
#define get_day 3
extern  int * get_day_3(dates *, CLIENT *);
extern  int * get_day_3_svc(dates *, struct svc_req *);
extern int tell_me_day3_3_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define get_day 3
extern  int * get_day_3();
extern  int * get_day_3_svc();
extern int tell_me_day3_3_freeresult ();
#endif /* K&R C */

#define TELL_ME_DAY4 0x1000004
#define TELL_ME_DAY_VERSION4 4

#if defined(__STDC__) || defined(__cplusplus)
#define get_no_of_weekday 4
extern  dates * get_no_of_weekday_4(dates *, CLIENT *);
extern  dates * get_no_of_weekday_4_svc(dates *, struct svc_req *);
extern int tell_me_day4_4_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define get_no_of_weekday 4
extern  dates * get_no_of_weekday_4();
extern  dates * get_no_of_weekday_4_svc();
extern int tell_me_day4_4_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_date (XDR *, date*);
extern  bool_t xdr_dates (XDR *, dates*);

#else /* K&R C */
extern bool_t xdr_date ();
extern bool_t xdr_dates ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TELLMEDAY_H_RPCGEN */
