/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "tellmeday.h"

dates *
no_leap_years_1_svc(dates *argp, struct svc_req *rqstp)
{
	static dates  result;

	/*
	 * insert server code here
	 */

	return &result;
}

dates *
no_of_days_2_svc(dates *argp, struct svc_req *rqstp)
{
	static dates  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
get_day_3_svc(dates *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

dates *
get_no_of_weekday_4_svc(dates *argp, struct svc_req *rqstp)
{
	static dates  result;

	/*
	 * insert server code here
	 */

	return &result;
}
