/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "tellmeday.h"


void
tell_me_day1_1(char *host)
{
	CLIENT *clnt;
	dates  *result_1;
	dates  no_leap_years_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, TELL_ME_DAY1, TELL_ME_DAY_VERSION1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = no_leap_years_1(&no_leap_years_1_arg, clnt);
	if (result_1 == (dates *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
tell_me_day2_2(char *host)
{
	CLIENT *clnt;
	dates  *result_1;
	dates  no_of_days_2_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, TELL_ME_DAY2, TELL_ME_DAY_VERSION2, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = no_of_days_2(&no_of_days_2_arg, clnt);
	if (result_1 == (dates *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
tell_me_day3_3(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	dates  get_day_3_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, TELL_ME_DAY3, TELL_ME_DAY_VERSION3, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = get_day_3(&get_day_3_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
tell_me_day4_4(char *host)
{
	CLIENT *clnt;
	dates  *result_1;
	dates  get_no_of_weekday_4_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, TELL_ME_DAY4, TELL_ME_DAY_VERSION4, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = get_no_of_weekday_4(&get_no_of_weekday_4_arg, clnt);
	if (result_1 == (dates *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	tell_me_day1_1 (host);
	tell_me_day2_2 (host);
	tell_me_day3_3 (host);
	tell_me_day4_4 (host);
exit (0);
}
