/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TELLMEDAY_H_RPCGEN
#define _TELLMEDAY_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct date {
	int dd;
	int mm;
	long yy;
};
typedef struct date date;

struct dates {
	date d1;
	date d2;
	long arg;
};
typedef struct dates dates;

struct args {
	int d1;
	int d2;
	int d;
	long days;
};
typedef struct args args;

#define TELL_ME_DAY 0x3987642
#define TELL_ME_DAY_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define no_leap_years 1
extern  int * no_leap_years_1(date *, CLIENT *);
extern  int * no_leap_years_1_svc(date *, struct svc_req *);
#define no_of_days 2
extern  long * no_of_days_1(dates *, CLIENT *);
extern  long * no_of_days_1_svc(dates *, struct svc_req *);
#define get_day 3
extern  int * get_day_1(dates *, CLIENT *);
extern  int * get_day_1_svc(dates *, struct svc_req *);
#define get_no_of_weekday 4
extern  long * get_no_of_weekday_1(args *, CLIENT *);
extern  long * get_no_of_weekday_1_svc(args *, struct svc_req *);
extern int tell_me_day_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define no_leap_years 1
extern  int * no_leap_years_1();
extern  int * no_leap_years_1_svc();
#define no_of_days 2
extern  long * no_of_days_1();
extern  long * no_of_days_1_svc();
#define get_day 3
extern  int * get_day_1();
extern  int * get_day_1_svc();
#define get_no_of_weekday 4
extern  long * get_no_of_weekday_1();
extern  long * get_no_of_weekday_1_svc();
extern int tell_me_day_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_date (XDR *, date*);
extern  bool_t xdr_dates (XDR *, dates*);
extern  bool_t xdr_args (XDR *, args*);

#else /* K&R C */
extern bool_t xdr_date ();
extern bool_t xdr_dates ();
extern bool_t xdr_args ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TELLMEDAY_H_RPCGEN */
