/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "tellmeday.h"

bool_t
xdr_date (XDR *xdrs, date *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->dd))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->mm))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->yy))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_dates (XDR *xdrs, dates *objp)
{
	register int32_t *buf;

	 if (!xdr_date (xdrs, &objp->d1))
		 return FALSE;
	 if (!xdr_date (xdrs, &objp->d2))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->arg))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_args (XDR *xdrs, args *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->d1))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->d2))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->d))
				 return FALSE;
			 if (!xdr_long (xdrs, &objp->days))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->d1);
			IXDR_PUT_LONG(buf, objp->d2);
			IXDR_PUT_LONG(buf, objp->d);
			IXDR_PUT_LONG(buf, objp->days);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->d1))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->d2))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->d))
				 return FALSE;
			 if (!xdr_long (xdrs, &objp->days))
				 return FALSE;
		} else {
			objp->d1 = IXDR_GET_LONG(buf);
			objp->d2 = IXDR_GET_LONG(buf);
			objp->d = IXDR_GET_LONG(buf);
			objp->days = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->d1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->d2))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->d))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->days))
		 return FALSE;
	return TRUE;
}
